/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7_paint;

import java.awt.BasicStroke;
import java.awt.Stroke;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author antonio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesFormas = new javax.swing.ButtonGroup();
        gurupoBotonesColores = new javax.swing.ButtonGroup();
        barraHerramientas = new javax.swing.JToolBar();
        botonPunto = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonElipse = new javax.swing.JToggleButton();
        panelInferior = new javax.swing.JPanel();
        barraEstado = new javax.swing.JLabel();
        panelOpcionesInferior = new javax.swing.JPanel();
        panelColores = new javax.swing.JPanel();
        panelAuxColores = new javax.swing.JPanel();
        bColor1 = new javax.swing.JToggleButton();
        bColor2 = new javax.swing.JToggleButton();
        bColor3 = new javax.swing.JToggleButton();
        bColor4 = new javax.swing.JToggleButton();
        bColor5 = new javax.swing.JToggleButton();
        bColor6 = new javax.swing.JToggleButton();
        panelGrosor = new javax.swing.JPanel();
        spinnerGrosor = new javax.swing.JSpinner();
        panelCheckBox = new javax.swing.JPanel();
        panelAuxCheckBox = new javax.swing.JPanel();
        botonRelleno = new javax.swing.JCheckBox();
        botonTransparencia = new javax.swing.JCheckBox();
        botonAlisar = new javax.swing.JCheckBox();
        botonEditar = new javax.swing.JCheckBox();
        escritorio = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        miVerBarraEstado = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Básico");

        barraHerramientas.setRollover(true);

        grupoBotonesFormas.add(botonPunto);
        botonPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Lapiz.gif"))); // NOI18N
        botonPunto.setSelected(true);
        botonPunto.setToolTipText("Punto");
        botonPunto.setFocusable(false);
        botonPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonPunto);

        grupoBotonesFormas.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Linea.gif"))); // NOI18N
        botonLinea.setToolTipText("Línea");
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLineaActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonLinea);

        grupoBotonesFormas.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rectangulo.gif"))); // NOI18N
        botonRectangulo.setToolTipText("Rectángulo");
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRectanguloActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonRectangulo);

        grupoBotonesFormas.add(botonElipse);
        botonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ovalo.gif"))); // NOI18N
        botonElipse.setToolTipText("Elipse");
        botonElipse.setFocusable(false);
        botonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElipseActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonElipse);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.PAGE_START);

        panelInferior.setLayout(new java.awt.BorderLayout());

        barraEstado.setText("Barra de estado");
        barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelInferior.add(barraEstado, java.awt.BorderLayout.PAGE_END);

        panelOpcionesInferior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOpcionesInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        panelColores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelColores.setMinimumSize(new java.awt.Dimension(45, 90));
        panelColores.setPreferredSize(new java.awt.Dimension(130, 90));
        panelColores.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelAuxColores.setLayout(new java.awt.GridLayout(2, 2, 2, 2));

        bColor1.setBackground(new java.awt.Color(0, 0, 0));
        gurupoBotonesColores.add(bColor1);
        bColor1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bColor1.setMaximumSize(new java.awt.Dimension(25, 25));
        bColor1.setMinimumSize(new java.awt.Dimension(25, 25));
        bColor1.setPreferredSize(new java.awt.Dimension(25, 25));
        bColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColor1ActionPerformed(evt);
            }
        });
        panelAuxColores.add(bColor1);

        bColor2.setBackground(new java.awt.Color(0, 255, 0));
        gurupoBotonesColores.add(bColor2);
        bColor2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bColor2.setMaximumSize(new java.awt.Dimension(25, 25));
        bColor2.setMinimumSize(new java.awt.Dimension(25, 25));
        bColor2.setPreferredSize(new java.awt.Dimension(25, 25));
        bColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColor2ActionPerformed(evt);
            }
        });
        panelAuxColores.add(bColor2);

        bColor3.setBackground(new java.awt.Color(0, 0, 255));
        gurupoBotonesColores.add(bColor3);
        bColor3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bColor3.setMaximumSize(new java.awt.Dimension(25, 25));
        bColor3.setMinimumSize(new java.awt.Dimension(25, 25));
        bColor3.setPreferredSize(new java.awt.Dimension(25, 25));
        bColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColor3ActionPerformed(evt);
            }
        });
        panelAuxColores.add(bColor3);

        bColor4.setBackground(new java.awt.Color(255, 255, 255));
        gurupoBotonesColores.add(bColor4);
        bColor4.setForeground(new java.awt.Color(255, 255, 255));
        bColor4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bColor4.setMaximumSize(new java.awt.Dimension(25, 25));
        bColor4.setMinimumSize(new java.awt.Dimension(25, 25));
        bColor4.setPreferredSize(new java.awt.Dimension(25, 25));
        bColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColor4ActionPerformed(evt);
            }
        });
        panelAuxColores.add(bColor4);

        bColor5.setBackground(new java.awt.Color(255, 255, 0));
        gurupoBotonesColores.add(bColor5);
        bColor5.setForeground(new java.awt.Color(255, 255, 0));
        bColor5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bColor5.setMaximumSize(new java.awt.Dimension(25, 25));
        bColor5.setMinimumSize(new java.awt.Dimension(25, 25));
        bColor5.setPreferredSize(new java.awt.Dimension(25, 25));
        bColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColor5ActionPerformed(evt);
            }
        });
        panelAuxColores.add(bColor5);

        bColor6.setBackground(new java.awt.Color(255, 0, 0));
        gurupoBotonesColores.add(bColor6);
        bColor6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bColor6.setMaximumSize(new java.awt.Dimension(25, 25));
        bColor6.setMinimumSize(new java.awt.Dimension(25, 25));
        bColor6.setPreferredSize(new java.awt.Dimension(25, 25));
        bColor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bColor6ActionPerformed(evt);
            }
        });
        panelAuxColores.add(bColor6);

        panelColores.add(panelAuxColores);

        panelOpcionesInferior.add(panelColores);

        panelGrosor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grosor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelGrosor.setToolTipText("");
        panelGrosor.setMinimumSize(new java.awt.Dimension(56, 90));
        panelGrosor.setPreferredSize(new java.awt.Dimension(70, 90));
        panelGrosor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 9));

        spinnerGrosor.setToolTipText("Borde");
        spinnerGrosor.setPreferredSize(new java.awt.Dimension(40, 40));
        spinnerGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerGrosorStateChanged(evt);
            }
        });
        panelGrosor.add(spinnerGrosor);

        panelOpcionesInferior.add(panelGrosor);

        panelCheckBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelCheckBox.setMinimumSize(new java.awt.Dimension(230, 90));
        panelCheckBox.setPreferredSize(new java.awt.Dimension(242, 90));
        panelCheckBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        panelAuxCheckBox.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        botonRelleno.setText("Relleno");
        botonRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRellenoActionPerformed(evt);
            }
        });
        panelAuxCheckBox.add(botonRelleno);

        botonTransparencia.setText("Transparencia");
        botonTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTransparenciaActionPerformed(evt);
            }
        });
        panelAuxCheckBox.add(botonTransparencia);

        botonAlisar.setText("Alisar");
        botonAlisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlisarActionPerformed(evt);
            }
        });
        panelAuxCheckBox.add(botonAlisar);

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        panelAuxCheckBox.add(botonEditar);

        panelCheckBox.add(panelAuxCheckBox);

        panelOpcionesInferior.add(panelCheckBox);
        panelCheckBox.getAccessibleContext().setAccessibleName("");

        panelInferior.add(panelOpcionesInferior, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);

        escritorio.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        miNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miNuevo.setText("Nuevo");
        miNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(miNuevo);

        miAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miAbrir.setText("Abrir");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(miAbrir);

        miGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miGuardar.setText("Guardar");
        miGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(miGuardar);

        barraMenu.add(menuArchivo);

        menuEditar.setText("Editar");

        miVerBarraEstado.setSelected(true);
        miVerBarraEstado.setText("Barra de Estado");
        miVerBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerBarraEstadoActionPerformed(evt);
            }
        });
        menuEditar.add(miVerBarraEstado);

        barraMenu.add(menuEditar);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna(this);
        escritorio.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_miNuevoActionPerformed

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //TODO
        }
    }//GEN-LAST:event_miAbrirActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setForma(sm.avj.ui.Forma.PUNTO);
        }
        //this.barraEstado.setText("Punto seleccionado");
        this.repaint();
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLineaActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setForma(sm.avj.ui.Forma.LINEA);
        }
        //this.barraEstado.setText("Linea seleccionada");
        this.repaint();
    }//GEN-LAST:event_botonLineaActionPerformed

    private void botonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRectanguloActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setForma(sm.avj.ui.Forma.RECTANGULO);
        }
        //this.barraEstado.setText("Rectangulo seleccionado");
        this.repaint();
    }//GEN-LAST:event_botonRectanguloActionPerformed

    private void botonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElipseActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setForma(sm.avj.ui.Forma.ELIPSE);
        }
        //this.barraEstado.setText("Elipse seleccionada");
        this.repaint();
    }//GEN-LAST:event_botonElipseActionPerformed

    private void botonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRellenoActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setRelleno(this.botonRelleno.isSelected());
        }
        this.repaint();
    }//GEN-LAST:event_botonRellenoActionPerformed

    private void bColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColor1ActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setColor(this.bColor1.getBackground());
        }
        this.repaint();
    }//GEN-LAST:event_bColor1ActionPerformed

    private void bColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColor2ActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setColor(this.bColor2.getBackground());
        }
        this.repaint();
    }//GEN-LAST:event_bColor2ActionPerformed

    private void bColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColor3ActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setColor(this.bColor3.getBackground());
        }
        this.repaint();
    }//GEN-LAST:event_bColor3ActionPerformed

    private void bColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColor4ActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setColor(this.bColor4.getBackground());
        }
        this.repaint();
    }//GEN-LAST:event_bColor4ActionPerformed

    private void bColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColor5ActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setColor(this.bColor5.getBackground());
        }
        this.repaint();
    }//GEN-LAST:event_bColor5ActionPerformed

    private void bColor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bColor6ActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setColor(this.bColor6.getBackground());
        }
        this.repaint();
    }//GEN-LAST:event_bColor6ActionPerformed

    private void miVerBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerBarraEstadoActionPerformed
        this.barraEstado.setVisible(this.miVerBarraEstado.isSelected());
    }//GEN-LAST:event_miVerBarraEstadoActionPerformed

    private void miGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //TODO
        }
    }//GEN-LAST:event_miGuardarActionPerformed

    private void botonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlisarActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setAlisado(this.botonAlisar.isSelected());
        }
        this.repaint();
    }//GEN-LAST:event_botonAlisarActionPerformed

    private void botonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransparenciaActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setTransparencia(this.botonTransparencia.isSelected());
        }
        this.repaint();
    }//GEN-LAST:event_botonTransparenciaActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo().setEditar(this.botonEditar.isSelected());
        }
        this.repaint();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void spinnerGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerGrosorStateChanged
        VentanaInterna vi = (VentanaInterna) this.escritorio.getSelectedFrame();
        if (vi != null) {
            Stroke st = new BasicStroke((Integer) this.spinnerGrosor.getValue());
            vi.getLienzo().setStroke(st);
        }
        this.repaint();
    }//GEN-LAST:event_spinnerGrosorStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JToggleButton bColor1;
    protected javax.swing.JToggleButton bColor2;
    protected javax.swing.JToggleButton bColor3;
    protected javax.swing.JToggleButton bColor4;
    protected javax.swing.JToggleButton bColor5;
    protected javax.swing.JToggleButton bColor6;
    protected javax.swing.JLabel barraEstado;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JMenuBar barraMenu;
    protected javax.swing.JCheckBox botonAlisar;
    protected javax.swing.JCheckBox botonEditar;
    protected javax.swing.JToggleButton botonElipse;
    protected javax.swing.JToggleButton botonLinea;
    protected javax.swing.JToggleButton botonPunto;
    protected javax.swing.JToggleButton botonRectangulo;
    protected javax.swing.JCheckBox botonRelleno;
    protected javax.swing.JCheckBox botonTransparencia;
    protected javax.swing.JDesktopPane escritorio;
    private javax.swing.ButtonGroup grupoBotonesFormas;
    private javax.swing.ButtonGroup gurupoBotonesColores;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miNuevo;
    private javax.swing.JCheckBoxMenuItem miVerBarraEstado;
    private javax.swing.JPanel panelAuxCheckBox;
    private javax.swing.JPanel panelAuxColores;
    private javax.swing.JPanel panelCheckBox;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelGrosor;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelOpcionesInferior;
    protected javax.swing.JSpinner spinnerGrosor;
    // End of variables declaration//GEN-END:variables
}
