/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamDiscoveryService;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamPicker;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

/**
 *
 * @author antonio
 */
public class VentanaInternaWebCam extends javax.swing.JInternalFrame {

    Webcam webcam = null;

    /**
     * Creates new form VentanaWebCam
     */
    public VentanaInternaWebCam() {
        initComponents();
        init();

        //Detengo la busqueda de camaras al encontar una
        //Quitando las dos siguientes lineas se queda buscando
        //Mientras la ventana siga abierta.
        WebcamDiscoveryService discovery = Webcam.getDiscoveryService();
        discovery.stop();
    }

    public BufferedImage getFrame() {
        BufferedImage img = null;
        if (webcam != null) {
            img = webcam.getImage();
        }
        return img;
    }

    private void init() {
        webcam = Webcam.getDefault();

        if (webcam != null) {
            WebcamPicker picker = new WebcamPicker();
            webcam = picker.getSelectedWebcam();
            webcam.setViewSize(WebcamResolution.VGA.getSize());

            WebcamPanel panel = new WebcamPanel(webcam, false);
            panel.setFPSDisplayed(true);

            add(picker, BorderLayout.NORTH);
            add(panel, BorderLayout.CENTER);

            pack();

            //Crear otra hebra para evitar bloquear el programa
            Thread t = new Thread() {
                @Override
                public void run() {
                    panel.start();
                }
            };

            t.start();

        } else {
            JOptionPane.showMessageDialog(this, "No se han detectado ninguna WebCam", "Error", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(320, 240));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        //WebcamDiscoveryService discovery = Webcam.getDiscoveryService();
        //discovery.stop();
        if (webcam != null) {
            webcam.close();
        }
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
