package sm.avj.ui;

import java.awt.Frame;

/**
 *
 * @author antonio
 */
public class ResizeDialog extends javax.swing.JDialog {

    Frame p;
    boolean editado;

    /**
     * Creates new form resizeDialog
     *
     * @param parent
     * @param modal
     */
    public ResizeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.editado = false;
        initComponents();
        p = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonRedimensionar = new javax.swing.JButton();
        panelSuperior = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        panelEditor = new javax.swing.JPanel();
        panelAlto = new javax.swing.JPanel();
        panelLabelAlto = new javax.swing.JPanel();
        labelAlto = new javax.swing.JLabel();
        panenTFAlto = new javax.swing.JPanel();
        textAlto = new javax.swing.JTextField();
        panelPxAlto = new javax.swing.JPanel();
        labelPxAlto = new javax.swing.JLabel();
        panelAncho = new javax.swing.JPanel();
        panelLabelAncho = new javax.swing.JPanel();
        labelAncho = new javax.swing.JLabel();
        panelTFAncho = new javax.swing.JPanel();
        textAncho = new javax.swing.JTextField();
        panelPxAncho = new javax.swing.JPanel();
        labelPxAncho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tamaño Imagen");
        setAlwaysOnTop(true);
        setResizable(false);

        panelBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 35, 5));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        botonRedimensionar.setText("Redimensionar");
        botonRedimensionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRedimensionarActionPerformed(evt);
            }
        });
        panelBotones.add(botonRedimensionar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSuperior.setLayout(new java.awt.GridLayout(0, 2));

        panelImagen.setLayout(new java.awt.BorderLayout());

        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagen.setIcon(new javax.swing.ImageIcon("/home/antonio/NetBeansProjects/Practica8/src/iconos/resize.png")); // NOI18N
        panelImagen.add(labelImagen, java.awt.BorderLayout.CENTER);

        panelSuperior.add(panelImagen);

        panelEditor.setLayout(new java.awt.GridLayout(2, 0));

        panelAlto.setLayout(new java.awt.GridLayout(1, 0));

        panelLabelAlto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 45));

        labelAlto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAlto.setText("Alto:  ");
        labelAlto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelLabelAlto.add(labelAlto);

        panelAlto.add(panelLabelAlto);

        panenTFAlto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        textAlto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textAlto.setText("300");
        textAlto.setPreferredSize(new java.awt.Dimension(60, 29));
        panenTFAlto.add(textAlto);

        panelAlto.add(panenTFAlto);

        panelPxAlto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 45));

        labelPxAlto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPxAlto.setText("px");
        panelPxAlto.add(labelPxAlto);

        panelAlto.add(panelPxAlto);

        panelEditor.add(panelAlto);

        panelAncho.setLayout(new java.awt.GridLayout(1, 0));

        labelAncho.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAncho.setText("Ancho:");
        panelLabelAncho.add(labelAncho);

        panelAncho.add(panelLabelAncho);

        panelTFAncho.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        textAncho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textAncho.setText("300");
        textAncho.setPreferredSize(new java.awt.Dimension(60, 29));
        panelTFAncho.add(textAncho);

        panelAncho.add(panelTFAncho);

        labelPxAncho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPxAncho.setText("px");
        panelPxAncho.add(labelPxAncho);

        panelAncho.add(panelPxAncho);

        panelEditor.add(panelAncho);

        panelSuperior.add(panelEditor);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getAltura() {
        return Integer.parseInt(this.textAlto.getText());
    }

    public int getAncho() {
        return Integer.parseInt(this.textAncho.getText());
    }

    public boolean getEditado() {
        return editado;
    }

    public void setEditado(boolean e) {
        editado = e;
    }

    public void setAltura(int alto) {
        this.textAlto.setText(Integer.toString(alto));
    }

    public void setAncho(int ancho) {
        this.textAncho.setText(Integer.toString(ancho));
    }

    private void botonRedimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedimensionarActionPerformed
        editado = true;
        this.dispose();
    }//GEN-LAST:event_botonRedimensionarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        editado = false;
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResizeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResizeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResizeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResizeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ResizeDialog dialog = new ResizeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRedimensionar;
    private javax.swing.JLabel labelAlto;
    private javax.swing.JLabel labelAncho;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelPxAlto;
    private javax.swing.JLabel labelPxAncho;
    private javax.swing.JPanel panelAlto;
    private javax.swing.JPanel panelAncho;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelLabelAlto;
    private javax.swing.JPanel panelLabelAncho;
    private javax.swing.JPanel panelPxAlto;
    private javax.swing.JPanel panelPxAncho;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTFAncho;
    private javax.swing.JPanel panenTFAlto;
    private javax.swing.JTextField textAlto;
    private javax.swing.JTextField textAncho;
    // End of variables declaration//GEN-END:variables
}
