/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.avj.ui;

import java.awt.Color;
import java.awt.Frame;

/**
 *
 * @author antonio
 */
public class SelectorColoresDialog extends javax.swing.JDialog {

    boolean seleccionado;
    Color colorFrente = Color.LIGHT_GRAY;
    Color colorFondo = Color.LIGHT_GRAY;

    /**
     * Creates new form SelectorColoresDialog
     */
    public SelectorColoresDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelColores = new javax.swing.JPanel();
        selectorColores = new javax.swing.JColorChooser();
        panelBotones = new javax.swing.JPanel();
        botonColorFrente = new javax.swing.JButton();
        botonColorFondo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelColores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelColores.setLayout(new java.awt.BorderLayout());
        panelColores.add(selectorColores, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelColores, java.awt.BorderLayout.CENTER);

        panelBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 35, 5));

        botonColorFrente.setText("Color Frente");
        botonColorFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorFrenteActionPerformed(evt);
            }
        });
        panelBotones.add(botonColorFrente);

        botonColorFondo.setText("Color Fondo");
        botonColorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorFondoActionPerformed(evt);
            }
        });
        panelBotones.add(botonColorFondo);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });
        panelBotones.add(botonSeleccionar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        seleccionado = true;
        this.dispose();
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        seleccionado = false;
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonColorFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorFrenteActionPerformed
        colorFrente = this.selectorColores.getColor();
        this.botonColorFrente.setBackground(colorFrente);
    }//GEN-LAST:event_botonColorFrenteActionPerformed

    private void botonColorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorFondoActionPerformed
        colorFondo = this.selectorColores.getColor();
        this.botonColorFondo.setBackground(colorFondo);
    }//GEN-LAST:event_botonColorFondoActionPerformed

    public boolean isSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }

    public Color getColorFondo() {
        return colorFondo;
    }

    public void setColorFondo(Color colorFondo) {
        this.colorFondo = colorFondo;
        this.botonColorFondo.setBackground(colorFondo);
    }

    public Color getColorFrente() {
        return colorFrente;
    }

    public void setColorFrente(Color c) {
        this.colorFrente = c;
        this.botonColorFrente.setBackground(colorFrente);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorColoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorColoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorColoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorColoresDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectorColoresDialog dialog = new SelectorColoresDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonColorFondo;
    private javax.swing.JButton botonColorFrente;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelColores;
    private javax.swing.JColorChooser selectorColores;
    // End of variables declaration//GEN-END:variables
}
